# Don't modify this file directly in Azure DevOps due to Gitlab mirroring to be one way.
# Push the changes on gitlab, it will be reflected in Azure DevOps after.
parameters:
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: debug
    values:
    - debug
    - release
  - name: buildPlatform
    displayName: Build Platform
    type: string
    default: any cpu
    values: 
    - any cpu
    - x86
    - x64
  - name: nugetFeed
    displayName: Deploy to Feed
    type: string
    default: No
    values:
    - No
    - Development Feed
    - Production Feed
  - name: packageVersion
    displayName: NuGet Package Version
    type: string
    default: '0.0.0'
trigger: none
variables:
  - name: BuildParameters.solution
    value: '**\*.sln'
  - name: PackageVersion
    value: '${{ parameters.packageVersion }}'
  - name: BuildConfiguration
    value: '${{ parameters.buildConfiguration }}'
  - name: BuildPlatform
    value: '${{ parameters.buildPlatform }}'
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/develop
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Azure Pipelines
    vmImage: windows-2022
  steps:
  - checkout: self
    clean: true
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 6.1.0
    inputs:
      versionSpec: 6.1.0
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: $(BuildParameters.solution)
  - task: VSBuild@1
    displayName: Build solution **\*.sln
    inputs:
      solution: $(BuildParameters.solution)
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: VSTest@2
    displayName: VsTest - testAssemblies
    inputs:
      testAssemblyVer2: >-
        **\$(BuildConfiguration)\*test*.dll

        !**\obj\**
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: NuGetCommand@2
    displayName: NuGet pack
    inputs:
      command: pack
      versioningScheme: byEnvVar
      versionEnvVar: PackageVersion
      includeSymbols: true
    condition: ne('${{ parameters.nugetFeed }}', 'No')
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: b8f3ec8a-abb9-4751-aff2-562771e75cc5
    condition: eq('${{ parameters.nugetFeed }}', 'Development Feed')
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: 0c681b63-1238-46ef-aee8-c1bf40f1785f
    condition: eq('${{ parameters.nugetFeed }}', 'Production Feed')
...
