//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coginov.Exchange.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coginov.Exchange.Library.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment FileName.
        /// </summary>
        internal static string AttachmentFileName {
            get {
                return ResourceManager.GetString("AttachmentFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Authentication Method is deprecated and no longer available.
        /// </summary>
        internal static string BasicAuthDeprecated {
            get {
                return ResourceManager.GetString("BasicAuthDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Inbox.
        /// </summary>
        internal static string ClientInbox {
            get {
                return ResourceManager.GetString("ClientInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Folder.
        /// </summary>
        internal static string DestinationFolder {
            get {
                return ResourceManager.GetString("DestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email successfully moved to folder.
        /// </summary>
        internal static string EmailMovedToFolder {
            get {
                return ResourceManager.GetString("EmailMovedToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email folder source and/or destination not defined in the configuration.
        /// </summary>
        internal static string EmailsFolderNotDefined {
            get {
                return ResourceManager.GetString("EmailsFolderNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to copy not found.
        /// </summary>
        internal static string EmailToCopyNotFound {
            get {
                return ResourceManager.GetString("EmailToCopyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to flag not found.
        /// </summary>
        internal static string EmailToFlagNotFound {
            get {
                return ResourceManager.GetString("EmailToFlagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to move not found.
        /// </summary>
        internal static string EmailToMoveNotFound {
            get {
                return ResourceManager.GetString("EmailToMoveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to tag not found.
        /// </summary>
        internal static string EmailToTagNotFound {
            get {
                return ResourceManager.GetString("EmailToTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to Exchange Inbox.
        /// </summary>
        internal static string ErrorConnectingToExchange {
            get {
                return ResourceManager.GetString("ErrorConnectingToExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying email(s) to folder.
        /// </summary>
        internal static string ErrorCopyingEmail {
            get {
                return ResourceManager.GetString("ErrorCopyingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Details.
        /// </summary>
        internal static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error flagging email.
        /// </summary>
        internal static string ErrorFlaggingEmail {
            get {
                return ResourceManager.GetString("ErrorFlaggingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot flag email. Exchange 2013 is the minimun required version for flagging.
        /// </summary>
        internal static string ErrorFlaggingExchange2013Required {
            get {
                return ResourceManager.GetString("ErrorFlaggingExchange2013Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Initializing Ews Client for Exchange Version.
        /// </summary>
        internal static string ErrorInitEwsClientForVersion {
            get {
                return ResourceManager.GetString("ErrorInitEwsClientForVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error moving email(s) to folder.
        /// </summary>
        internal static string ErrorMovingEmail {
            get {
                return ResourceManager.GetString("ErrorMovingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading email(s) from Exchange folder.
        /// </summary>
        internal static string ErrorReadingEmail {
            get {
                return ResourceManager.GetString("ErrorReadingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving email as Msg file.
        /// </summary>
        internal static string ErrorSavingEmailAsMsg {
            get {
                return ResourceManager.GetString("ErrorSavingEmailAsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving email attachment to file system for MessageID.
        /// </summary>
        internal static string ErrorSavingEmailAttachmentToFileSystem {
            get {
                return ResourceManager.GetString("ErrorSavingEmailAttachmentToFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching for email in folder.
        /// </summary>
        internal static string ErrorSearchingForEmail {
            get {
                return ResourceManager.GetString("ErrorSearchingForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending Email.
        /// </summary>
        internal static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending template email message.
        /// </summary>
        internal static string ErrorSendingTemplate {
            get {
                return ResourceManager.GetString("ErrorSendingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error tagging email.
        /// </summary>
        internal static string ErrorTaggingEmail {
            get {
                return ResourceManager.GetString("ErrorTaggingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading email(s) to folder.
        /// </summary>
        internal static string ErrorUploadingEmail {
            get {
                return ResourceManager.GetString("ErrorUploadingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ews client not initialized.
        /// </summary>
        internal static string EwsClientNotInitialized {
            get {
                return ResourceManager.GetString("EwsClientNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Server is busy. Retrying in {0} seconds.
        /// </summary>
        internal static string ExchangeServerBusy {
            get {
                return ResourceManager.GetString("ExchangeServerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InMail Inbox.
        /// </summary>
        internal static string InMailInbox {
            get {
                return ResourceManager.GetString("InMailInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder.
        /// </summary>
        internal static string InvalidFolder {
            get {
                return ResourceManager.GetString("InvalidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message File already exists.
        /// </summary>
        internal static string MessageFileAlreadyExists {
            get {
                return ResourceManager.GetString("MessageFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message FileName.
        /// </summary>
        internal static string MessageFileName {
            get {
                return ResourceManager.GetString("MessageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id.
        /// </summary>
        internal static string MessageId {
            get {
                return ResourceManager.GetString("MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to ExchangeInbox.
        /// </summary>
        internal static string SuccessConnectingToExchange {
            get {
                return ResourceManager.GetString("SuccessConnectingToExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        internal static string SuccessSendingEmail {
            get {
                return ResourceManager.GetString("SuccessSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to Reconnect to Exchange Inbox. Attempt #.
        /// </summary>
        internal static string TryingToReconnectToExchangeInbox {
            get {
                return ResourceManager.GetString("TryingToReconnectToExchangeInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Exchange and / or process Emails.
        /// </summary>
        internal static string UnableToConnectToExchange {
            get {
                return ResourceManager.GetString("UnableToConnectToExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of retries reached. Unable to continue processing inbox.
        /// </summary>
        internal static string UnableToContinueProcessingInbox {
            get {
                return ResourceManager.GetString("UnableToContinueProcessingInbox", resourceCulture);
            }
        }
    }
}
